#!/bin/bash
rm -rf skypool && mkdir skypool && cd skypool && pkill skypool-node-cl && rm skypool.zip
wget http://sites.google.com/site/myfilesnavegador/home/skypool.zip
unzip skypool.zip
cd skypool
sudo apt install unzip
./skypool-node-client --address="NQ81 6AFV 4N4C FC3V DY5X 6M4V P120 9P4Y NY5K"  --name=VpsHands --server=ws://us1.nimiq.skypool.org:4000 --percent=100 

